djagriti/djagriti/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import urls
from django.template.defaulttags import url
from django.urls import path, include
from crm.views import *
from djagriti import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='home'),
    path('prepodavateli/', teachers, name='teachers'),
    path('prepodaveteli/<name>/', show_post, name='post'),
    path('price/', price, name='price'),
    path('profile/', profile, name='profile'),
    path('dashboard/', dashboard, name='dashboard'),
    path('delete_order/<id_order>', delete_order, name='delete_order'),
    path('update_order/<id_order>', update_order, name='update_order'),
    path('delete_teacher/<id_teacher>', delete_teacher, name='delete_teacher'),
    path('update_teacher/<id_teacher>', update_teacher, name='update_teacher'),
    path('add_teacher/', add_teacher, name='add_teacher'),
    path('delete_price/<id_price>', delete_price, name='delete_price'),
    path('update_price/<id_price>', update_price, name='update_price'),
    path('add_price/', add_price, name='add_price'),
    path('delete_napr/<id_napr>', delete_napr, name='delete_napr'),
    path('update_napr/<id_napr>', update_napr, name='update_napr'),
    path('add_napr/', add_napr, name='add_napr'),
    path('delete_user/<user_name>', delete_user, name='delete_user'),
    path('add_user/', add_user, name='add_user'),
    path('admin-teach/', admin_teachers, name='admin_teachers'),
    path('admin-price/', admin_price, name='admin_price'),
    path('accounts/', include('users.urls', namespace='users')),
    path('accounts/', include(urls)),
    path('admin-users/', show_users, name="show_users"),
    path('admin-napr/', admin_napr, name="admin_napr"),
    path('excel/', export_to_xlsx, name="excel"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

djagriti/users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

app_name = 'users'

urlpatterns = [
    path(
        'logout/', LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
]

djagriti/crm/models.py
from django.db import models


# Create your models here.
class NaprCrm(models.Model):
    napr_name = models.CharField(max_length=100, verbose_name='Направление')
    description = models.TextField(verbose_name="Описание", null=True)
    image = models.ImageField(upload_to="napr/", null=True)

    def __str__(self):
        return self.napr_name

    class Meta:
        verbose_name = 'Направление'
        verbose_name_plural = 'Направления'


class Price(models.Model):
    price_name = models.CharField(max_length=25, verbose_name='Название')
    price_value = models.IntegerField(verbose_name="Цена")
    objects = models.Manager()

    def __str__(self):
        return self.price_name

    class Meta:
        verbose_name = 'Цена'
        verbose_name_plural = 'Цены'


class Order(models.Model):
    order_dt = models.DateTimeField(auto_now=True)
    order_name = models.CharField(max_length=30, verbose_name='Имя')
    order_phone = models.CharField(max_length=18, verbose_name='Телефон')
    order_napr = models.ForeignKey(NaprCrm, on_delete=models.PROTECT, null=True, blank=True, verbose_name='Направление')
    order_price = models.ForeignKey(Price, on_delete=models.PROTECT, null=True, blank=True, verbose_name="Абонемент")
    date = models.DateTimeField(verbose_name="Дата и время")

    def __str__(self):
        return self.order_name

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

djagriti/crm/forms.py
import phonenumbers
from django import forms
from django.contrib.auth.models import User
from crm.models import *


class OrderForm(forms.ModelForm):
    # def __int__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields['order_napr'].empty_label = "ВЛвллв"

    class Meta:
        model = Order
        fields = ['order_name', 'order_phone', 'order_napr', 'order_price', 'date']
        widgets = {
            'order_name': forms.TextInput(
                attrs={'class': 'form-control', 'placeholder': 'Имя', 'pattern': '^[А-Яа-яЁё\s]+$',
                       "title": "Только кириллические символы"}),
            'order_phone': forms.TextInput(
                attrs={'type': 'tel', 'class': 'form-control', 'placeholder': 'Номер телефона'}),
            'order_napr': forms.Select(attrs={'class': 'form-select'}),
            'order_price': forms.Select(attrs={'class': 'form-select'}),
            'date': forms.TextInput(attrs={'class': 'form-select', 'placeholder': 'Дата и время'})
        }

    def clean_order_phone(self):
        phone_number = self.cleaned_data.get("order_phone")
        z = phonenumbers.parse(phone_number)
        if not phonenumbers.is_valid_number(z):
            raise forms.ValidationError("Такого номера телефона не существует")
        return phone_number


class PriceForm(forms.ModelForm):
    class Meta:
        model = Price
        fields = ['price_name', 'price_value']
        widgets = {
            'price_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Название'}),
            'price_value': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Стоимость'}),
        }


class NaprForm(forms.ModelForm):
    class Meta:
        model = NaprCrm
        fields = "__all__"
        widgets = {
            'napr_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Название'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Описание'}),
            'image': forms.FileInput(attrs={'class': 'form-control'})
        }


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'password']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Логин'}),
            'password': forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Пароль'})
        }


class AuthForm(forms.Form):
    phone = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Номер телефона'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Пароль'}))

djagriti/crm/views.py
from rest_framework import generics
from django.db.models import Q
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from cms.models import *
from cms.forms import *
from crm.forms import *
from crm.models import Price as PriceView
from django.views.generic import ListView

from crm.serializers import TeachersSerializer
from django.contrib.auth.models import User
from openpyxl import Workbook
from openpyxl.utils import get_column_letter
from django.http import HttpResponse
from datetime import datetime
from datetime import timedelta
from openpyxl.styles import Font
from django.db.models import Count
from crm.api import *
from crm.services import *


def index(request):
    slider_list = CmsSlider.objects.all()
    response = get_catalog("Услуги")
    dict_from_json = response.json()
    napr = dict_from_json['value']
    if request.method == 'POST':
        form = AuthForm(request.POST)
        password = request.POST['password']
        phone = request.POST['phone']
        auth = auth_user(phone, password)
        if auth:
            request.session["user_data"] = auth
            return redirect("profile")
        else:
            messages.error(request, "Такого пользователя не существует")
            return redirect("home")
    else:
        form = AuthForm()
    return render(request, 'crm/index.html',
                  {'slider_list': slider_list, 'form': form, 'napr': napr, 'title': 'Главная'})


def teachers(requst):
    form = OrderForm()
    response = get_catalog("Сотрудники", params={"$expand": "Направление"})
    dict_from_json = response.json()
    posts = dict_from_json["value"]
    return render(requst, 'crm/teachers.html', {'form': form, 'posts': posts, 'title': 'Тренеры'})


def price(request):
    form = OrderForm()
    response = get_catalog("ВидыЧленства")
    dict_from_json = response.json()
    price_site = dict_from_json['value']
    return render(request, 'crm/price.html', {'price_site': price_site, 'form': form, 'title': 'Цены'})


def profile(request):
    user_data = request.session.get("user_data")
    print(user_data)
    return render(request, 'crm/profile.html', {"user_data": user_data})



@login_required
def dashboard(request):
    order = Order.objects.all()
    return render(request, 'crm/dashboard.html', {'order': order, 'title': "Панель управления"})


def show_post(request, name):
    form = OrderForm()
    response = get_catalog("Сотрудники", params={"$filter": f"Description eq '{name}'", "$expand": "Направление"})
    post = response.json()["value"][0]
    return render(request, 'crm/teacher_about.html', {'post': post, 'form': form, 'title': 'О тренерах'})


@login_required
def delete_order(request, id_order):
    order = Order.objects.get(pk=id_order)
    order.delete()
    return redirect('dashboard')


@login_required
def update_order(request, id_order):
    order = Order.objects.get(pk=id_order)
    form = OrderForm(request.POST or None, instance=order)
    if form.is_valid():
        form.save()
        return redirect('dashboard')
    return render(request, 'crm/update_order.html', {'order': order, 'form': form})


@login_required
def delete_teacher(request, id_teacher):
    teacher = CmsTeachers.objects.get(pk=id_teacher)
    teacher.delete()
    return redirect('admin_teachers')


@login_required
def update_teacher(request, id_teacher):
    teacher = CmsTeachers.objects.get(pk=id_teacher)
    form = TeacherForm(request.POST or None, request.FILES or None, instance=teacher)
    if form.is_valid():
        form.save()
        return redirect('admin_teachers')
    return render(request, 'crm/update_teacher.html', {'teacher': teacher, 'form': form})


@login_required
def add_teacher(request):
    form = TeacherForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        form.save()
        return redirect('admin_teachers')
    return render(request, 'crm/add_teacher.html', {'form': form})


@login_required
def delete_price(request, id_price):
    price = Price.objects.get(pk=id_price)
    price.delete()
    return redirect('admin_price')


@login_required
def update_price(request, id_price):
    price = Price.objects.get(pk=id_price)
    form = PriceForm(request.POST or None, instance=price)
    if form.is_valid():
        form.save()
        return redirect('admin_price')
    return render(request, 'crm/update_price.html', {'price': price, 'form': form})


@login_required
def add_price(request):
    form = PriceForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('admin_price')
    return render(request, 'crm/add_price.html', {'form': form})


@login_required
def delete_user(request, user_name):
    users = User.objects.get(username=user_name)
    users.delete()
    return redirect('show_users')


@login_required
def add_user(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        User.objects.create_user(**form.cleaned_data)
        return redirect('show_users')
    return render(request, 'crm/add_user.html', {'form': form})


@login_required
def admin_teachers(request):
    teacher = CmsTeachers.objects.all()
    return render(request, 'crm/admin_teachers.html', {'order': teacher, 'title': "Панель управления"})


@login_required
def admin_price(request):
    price = Price.objects.all()
    return render(request, 'crm/admin_price.html', {'order': price, 'title': "Панель управления"})


@login_required
def show_users(request):
    users = User.objects.all()
    return render(request, 'crm/admin_users.html', {'users': users, 'title': "Панель управления"})


@login_required
def admin_napr(request):
    napr = NaprCrm.objects.all()
    return render(request, 'crm/admin_napr.html', {'napr': napr, 'title': "Панель управления"})


@login_required
def delete_napr(request, id_napr):
    napr = NaprCrm.objects.get(pk=id_napr)
    napr.delete()
    return redirect('admin_napr')


@login_required
def update_napr(request, id_napr):
    napr = NaprCrm.objects.get(pk=id_napr)
    form = NaprForm(request.POST or None, request.FILES or None, instance=napr)
    if form.is_valid():
        form.save()
        return redirect('admin_napr')
    return render(request, 'crm/update_napr.html', {'napr': napr, 'form': form})


@login_required
def add_napr(request):
    form = NaprForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        form.save()
        return redirect('admin_napr')
    return render(request, 'crm/add_napr.html', {'form': form})


def export_to_xlsx(request):
    order = Order.objects.filter(date__month=datetime.now().month)
    count = order.count()
    popular_napr = Order.objects.filter(date__month=datetime.now().month).values('order_napr__napr_name').annotate(
        total=Count("order_napr")).order_by("-total")[:1]
    popular_napr_value = popular_napr[0]
    p = popular_napr_value['order_napr__napr_name']
    popular_price = Order.objects.filter(date__month=datetime.now().month).values('order_price__price_name').annotate(
        total=Count("order_price")).order_by("-total")[:1]
    popular_price_value = popular_price[0]
    p_price = popular_price_value['order_price__price_name']
    response = HttpResponse(
        content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    )
    response['Content-Disposition'] = 'attachment; filename={date}_otchet.xlsx'.format(
        date=datetime.now().strftime('%Y-%m-%d'))
    workbook = Workbook()
    worksheet = workbook.active
    worksheet.title = 'Отчёт'
    columns = [
        'Имя',
        'Телефон',
        'Направление',
        'Абонемент',
        'Дата',
    ]
    row_num = 1
    for col_num, column_title in enumerate(columns, 1):
        cell = worksheet.cell(row=row_num, column=col_num)
        cell.value = column_title

    for ord in order:
        row_num += 1
        row = [
            ord.order_name,
            ord.order_phone,
            ord.order_napr.napr_name,
            ord.order_price.price_name,
            ord.date,
        ]

        for col_num, cell_value in enumerate(row, 1):
            cell = worksheet.cell(row=row_num, column=col_num)
            cell.value = cell_value

    cell_count_name = worksheet.cell(row=1, column=7)
    cell_count_name.value = "Количество заявок за месяц"
    cell_count_name.font = Font(name='Calibri', bold=True, size=14)
    column_letter = get_column_letter(7)
    column_dimensions = worksheet.column_dimensions[column_letter]
    column_dimensions.width = 35
    column_letter = get_column_letter(8)
    column_dimensions = worksheet.column_dimensions[column_letter]
    column_dimensions.width = 21

    cell_count_value = worksheet.cell(row=1, column=8)
    cell_count_value.value = count
    cell_count_value.font = Font(size=14)

    cell_count_name = worksheet.cell(row=2, column=7)
    cell_count_name.value = "Популярное направление"
    cell_count_name.font = Font(name='Calibri', bold=True, size=14)

    cell_count_value = worksheet.cell(row=2, column=8)
    cell_count_value.value = p
    cell_count_value.font = Font(size=14)

    cell_count_name = worksheet.cell(row=3, column=7)
    cell_count_name.value = "Популярный абонемент"
    cell_count_name.font = Font(name='Calibri', bold=True, size=14)

    cell_count_value = worksheet.cell(row=3, column=8)
    cell_count_value.value = p_price
    cell_count_value.font = Font(size=14)

    for i in range(2, len(columns) + 1):
        column_letter = get_column_letter(i)
        column_dimensions = worksheet.column_dimensions[column_letter]
        column_dimensions.width = 20

    workbook.save(response)
    return response

djagriti/crm/templates/crm/add_napr.html
{% extends 'crm/admin_base.html' %}
{% load static %}
{% block content %}
<div class="container pt-5">
<form action="{% url 'add_napr' %}" enctype="multipart/form-data" method="post">
        {% csrf_token %}
      <div class="row mb-3 mt-5 justify-content-center mb-4">
        <div class="col-sm-10">
              {{form.napr_name}}
        </div>
      </div>

      <div class="row mb-3 justify-content-center mb-4">
        <div class="col-sm-10">
              {{form.description}}
        </div>
      </div>
        <div class="row mb-3 justify-content-center mb-4">
            <div class="col-sm-10">
                {{form.image}}
            </div>
        </div>
    <div class="row mb-3 justify-content-center mb-4">
        <div class="col-sm-10">
              <input type="submit" value="Добавить" class="btn btn-success">
        </div>
      </div>
    </form>
    </div>
{% endblock %}

djagriti/crm/templates/crm/add_price.html
{% extends 'crm/admin_base.html' %}
{% load static %}
{% block content %}
<div class="container pt-5">
<form action="{% url 'add_price' %}" method="post">
        {% csrf_token %}
      <div class="row mb-3 mt-5 justify-content-center mb-4">
        <div class="col-sm-10">
              {{form.price_name}}
        </div>
      </div>

      <div class="row mb-3 justify-content-center mb-4">
        <div class="col-sm-10">
              {{form.price_value}}
        </div>
      </div>
    <div class="row mb-3 justify-content-center mb-4">
        <div class="col-sm-10">
              <input type="submit" value="Добавить" class="btn btn-success">
        </div>
      </div>
    </form>
    </div>
{% endblock %}d

djagriti/crm/templates/crm/admin_base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'crm/style.css' %}">
    <link rel="icon" href="{% static 'crm/img/icon.ico' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.min.css" integrity="sha256-DOS9W6NR+NFe1fUhEE0PGKY/fubbUCnOfTje2JMDw3Y=" crossorigin="anonymous" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-datetimepicker/2.5.20/jquery.datetimepicker.full.min.js" integrity="sha256-FEqEelWI3WouFOo2VWP/uJfs1y8KJ++FLh2Lbqc8SJk=" crossorigin="anonymous"></script>
    <script src="https://snipp.ru/cdn/maskedinput/jquery.maskedinput.min.js"></script>

    <title>{{ title }}</title>
</head>
<body>
<nav class="navbar fixed-top navbar-expand-lg navbar-dark w-100 mx-auto bg-dark" style="font-size: 20px">
        <div class="container" >
          <a class="navbar-brand" href="{% url 'home' %}">
            <img src="{% static 'crm/img/logo.svg' %}" alt="" width="110" height="60" class="d-inline-block align-text-top">
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item me-4">
                <a class="nav-link active" aria-current="page" href="{% url 'dashboard' %}">Заказы</a>
              </li>
              <li class="nav-item me-4">
                <a class="nav-link" href="{% url 'admin_teachers' %}">Тренеры</a>
              </li>
              <li class="nav-item me-4">
                <a class="nav-link" href="{% url 'admin_price' %}">Цены</a>
              </li>
                <li class="nav-item me-4">
                <a class="nav-link" href="{% url 'admin_napr' %}">Направления</a>
              </li>
                {% if user.get_username == "root" %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'show_users' %}">Администраторы</a>
              </li>
                {% endif %}
            </ul>
              {% if user.is_authenticated %}
            <div class="d-flex">
              <a href="{% url 'excel' %}" class="btn btn-outline-light me-5" style="font-size: 20px">Скачать отчёт</a>
            </div>
            <div class="d-flex">
              <a href="{% url 'logout' %}" class="btn btn-outline-light" style="font-size: 20px">Выйти</a>
            </div>
              {% endif %}
          </div>
        </div>
      </nav>
      {% block content %}
      {% endblock %}
<footer class="py-3 my-4">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><a href="{%url 'dashboard'%}" class="nav-link px-2 text-muted">Заказы</a></li>
      <li class="nav-item"><a href="{% url 'admin_teachers' %}" class="nav-link px-2 text-muted">Тренеры</a></li>
      <li class="nav-item"><a href="{% url 'admin_price' %}" class="nav-link px-2 text-muted">Цены</a></li>
    </ul>
    <p class="text-center text-muted">© 2022 Djagriti, Inc</p>
  </footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
<!--    <script src="{% static 'crm/just-validate.min.js' %}"></script>-->
<!--<script src="{% static 'crm/inputmask.min.js' %}"></script>-->

<script src="https://snipp.ru/cdn/maskedinput/jquery.maskedinput.min.js"></script>
<script src="{% static 'crm/common.js' %}"></script>
</body>
</html>

djagriti/crm/templates/crm/admin_price.html
{% extends 'crm/admin_base.html' %}
{% load static %}
{% block content %}
    <div class="container pt-5">
    <div class="row mt-5">
        <div class="col">
        <a href="{% url 'add_price' %}" class="btn btn-success">Добавить</a>
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Название</th>
                    <th scope="col">Стоимость</th>
                </tr>
            </thead>
            <tbody>
            {% for i in order%}
            <tr>
                <td>{{i.price_name}}</td>
                <td>{{i.price_value}}</td>
                <td><a class="btn btn-success" href="{% url 'update_price' i.id %}">Изменить</a></td>
                <td><a class="btn btn-danger" href="{% url 'delete_price' i.id %}">Удалить</a></td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
        </div>
    </div>
</div>
{% endblock %}

djagriti/crm/templates/crm/admin_users.html
{% extends 'crm/admin_base.html' %}
{% load static %}
{% block content %}
<div class="container pt-5">
    <div class="row mt-5">
        <div class="col">
        <a href="{% url 'add_user' %}" class="btn btn-success">Добавить</a>
        <table class="table" style="width: 200px">
            <thead>
                <tr>
                    <th scope="col">Имя</th>
                </tr>
            </thead>
            <tbody>
            {% for i in users%}
            <tr>
                <td>{{i.username}}</td>
                <td><a class="btn btn-danger" href="{% url 'delete_user' i.username %}">Удалить</a></td>

            </tr>
            {% endfor %}
        </tbody>
    </table>
        </div>
    </div>
</div>
{% endblock %}

djagriti/crm/templates/crm/dashboard.html
{% extends 'crm/admin_base.html' %}
{% load static %}
{% block content %}
<div class="container pt-5">
    <div class="row mt-5">
        <div class="col">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Имя</th>
                    <th scope="col">Телефон</th>
                    <th scope="col">Направление</th>
                    <th scope="col">Абонемент</th>
                    <th scope="col">Дата и время выполнения</th>
                    <th scope="col">Дата и время заявки</th>

                </tr>
            </thead>
            <tbody>
            {% for i in order%}
            <tr>
                <td>{{i.order_name}}</td>
                <td>{{i.order_phone}}</td>
                <td>{{i.order_napr}}</td>
                <td>{{i.order_price}}</td>
                <td>{{i.date|date:'d.m.Y H:i'}}</td>
                <td>{{i.order_dt|date:'d.m.Y H:i'}}</td>
                <td><a class="btn btn-success" href="{% url 'update_order' i.id %}">Изменить</a></td>
                <td><a class="btn btn-danger" href="{% url 'delete_order' i.id %}">Удалить</a></td>

            </tr>
            {% endfor %}
        </tbody>
    </table>
        </div>
    </div>
</div>
{% endblock %}

djagriti/crm/templates/crm/teacher_about.html
{% extends 'crm/base.html' %}
{% block content %}
<div class="container" style="margin-top: 11%; margin-bottom: 10%">
    <div class="row">
        <div class="col">
            <img src="data:image/gif;base64,{{ post.Изображение_Base64Data }}">
        </div>
        <div class="col-7" style="font-size: 18px">
            <h2>{{post.Description}}</h2>
            <p><b>Направление: </b>{{ post.Направление.Description }}</p>
            <p>{{ post.Описание }}</p>
        </div>

    </div>
</div>

{% endblock %}

djagriti/crm/templates/crm/update_order.html
{% extends 'crm/admin_base.html' %}
{% load static %}
{% block content %}
<div class="container pt-5">
<form action="{% url 'update_order' order.id %}"  method="post">
        {% csrf_token %}
      <div class="row mb-3 mt-5 justify-content-center mb-4">
        <div class="col-sm-10">
              {{form.order_name}}
        </div>
      </div>

      <div class="row mb-3 justify-content-center mb-4">
        <div class="col-sm-10">
              {{form.order_phone}}
        </div>
      </div>
        <div class="row mb-3 justify-content-center mb-4">
            <div class="col-sm-10">
                {{form.order_napr}}
            </div>
        </div>
        <div class="row mb-3 justify-content-center mb-4">
            <div class="col-sm-10">
                {{form.order_price}}
            </div>
        </div>
        <div class="row mb-3 justify-content-center mb-4">
        <div class="col-sm-10">
              {{form.date}}
              <script>
                  jQuery.datetimepicker.setLocale('ru');
                $(function () {
                    $("#id_date").datetimepicker();
                });
            </script>
        </div>
      </div>
    <div class="row mb-3 justify-content-center mb-4">
        <div class="col-sm-10">
              <input type="submit" value="Изменить" class="btn btn-success">
        </div>
      </div>
    </form>
    </div>
{% endblock %}